import os
Import('env', 'qt_env', 'arch', 'common', 'messaging', 'visionipc',
       'cereal', 'transformations')

base_frameworks = qt_env['FRAMEWORKS']
base_libs = [common, messaging, cereal, visionipc, transformations, 'zmq',
             'capnp', 'kj', 'm', 'ssl', 'crypto', 'pthread'] + qt_env["LIBS"]

qt_libs = ['qt_util'] + base_libs
replay_libs = qt_libs
qt_env.Program("ws", ["ws.cc", "main.cc"], LIBS=replay_libs, FRAMEWORKS=base_frameworks)

